version: '3.2'

services:
  db:
    image: mysql:8.0
    env_file: ./.env
    ports:
      - 4306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src/public:/var/www/public
      - ./src/tmp:/var/www/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mysql-data:
